abort builds on fail
bitrise-steplib/bitrise-step-build-router-wait pull request #10
Opened 2020-08-04 01:26 UTC by DamienBitrise

2020-08-04 01:27 UTC, DamienBitrise commented on vendor/github.com/bitrise-steplib/bitrise-step-build-router-start/bitrise/bitrise.go
> +	params["abort_reason"] = abortReason
This does not show up as the abort reason when the abort request is set.

Any ideas why this might be the case?

2020-08-04 01:28 UTC, DamienBitrise commented on vendor/github.com/bitrise-steplib/bitrise-step-build-router-start/bitrise/bitrise.go
> +	rm := abortRequest{BuildAbortParams: b}
Is this correct?

2020-08-04 03:57 UTC, DamienBitrise commented on vendor/github.com/bitrise-steplib/bitrise-step-build-router-start/bitrise/bitrise.go
> +	rm := abortRequest{BuildAbortParams: b}
Abort API shows
![image](https://user-images.githubusercontent.com/60897705/89251436-dbbe9880-d5cb-11ea-81fc-ca7ea4caff5e.png)

2020-08-05 10:49 UTC, trapacska requested changes
the same commants as here: https://github.com/bitrise-steplib/bitrise-step-build-router-start/pull/18#pullrequestreview-461543708

2020-08-05 15:47 UTC, trapacska approved these changes

2020-08-05 16:47 UTC, merged